[build]
  # Directorio de archivos a publicar
  publish = "."

  # Comando de build (no necesario para este proyecto estático)
  command = "echo 'Static site - no build needed'"

[build.environment]
  # Variables de entorno
  NODE_VERSION = "18"

[[headers]]
  # Headers para todos los archivos
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Headers específicos para el archivo principal
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Headers para archivos estáticos
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuración de formularios (si necesitas contacto)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

# Configuración para GitHub Pages también
[[redirects]]
  from = "/parte-diario-trabajo/*"
  to = "/index.html"
  status = 200

# Redirect para compatibilidad
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["*"]}